accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.list_accounts, name='list_accounts'),
    path('transaction/', views.transaction, name='transaction'),
    path('import_accounts/', views.import_accounts, name='import_accounts'),
    path('account_detail/<str:slug>/', views.account_detail, name='account_detail'),
    path('account_search/', views.account_search, name='account_search'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.urls
from django.conf.urls import handler404, handler500

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
]

handler404 = "accounts.views.error_404"
handler500 = "accounts.views.error_500"

accounts/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
import uuid

class Account(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(unique=True, max_length=150)

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.name)
            unique_slug = base_slug
            counter = 1

            while Account.objects.filter(slug=unique_slug).exclude(id=self.id).exists():
                unique_slug = f"{base_slug}-{uuid.uuid4().hex[:8]}"  # Use UUID for uniqueness

            self.slug = unique_slug

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    
    
class Transaction(models.Model):
    sender = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='receiver')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField()    
    def __str__(self):
        return f'{self.sender} sent {self.amount} to {self.receiver}'
    class Meta:
        ordering = ['-date']
    def save(self, *args, **kwargs):
        if not self.date:
            self.date = timezone.now()
        
        super().save(*args, **kwargs)
    
    

accounts/views.py
from django.shortcuts import render , redirect
from .models import Account , Transaction
from django.db import transaction as transactiondb
import csv
from django.core.paginator import Paginator
from django.contrib import messages
from decimal import Decimal

# Create your views here.
def validate_file(file):
    if not file.name.endswith('.csv'):
        context={'error': 'Invalid file type'}
        return context
    if file.size == 0:
        context={'error': 'Empty file'}
        return context
    
    context={'error': None}
    return context


def import_accounts(request):
    if request.method == 'POST':
        try:
            file = request.FILES['csv_file']
        except:
            messages.error(request, 'No file uploaded')
            return render(request, 'import_accounts.html')
        context = validate_file(file)
        if context['error']:
            messages.error(request, context['error'])
            return render(request, 'import_accounts.html')
        decoded_file = file.read().decode('utf-8').splitlines()
        reader = csv.reader(decoded_file)
        for row in reader:
            if row[0] == 'ID':
                continue
            try:
                account = Account(
                    id=row[0],
                    name=row[1],
                    balance=row[2]
                )
                account.save()
            except Exception as e:
                #skip the row if there is an error and create message with this error and row number
                messages.error(request, f'Error importing row {reader.line_num} => {row} with error {e}')
                continue
        messages.success(request, 'Accounts imported successfully')
    return render(request, 'import_accounts.html')


def list_accounts(request):
    accounts = Account.objects.all()
    paginator = Paginator(accounts, 100)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    total_accounts = accounts.count()
    total_balance = sum([account.balance for account in accounts])
    context = {
        'accounts': page_obj,
        'total_accounts': total_accounts,
        'total_balance': total_balance,
    }
    return render(request, 'list_accounts.html', context)


def account_detail(request, slug):
    account = Account.objects.get(slug=slug)
    transactions_send = Transaction.objects.filter(sender=account).select_related('receiver')
    transactions_receive = Transaction.objects.filter(receiver=account).select_related('sender')
    context={'account': account, 'send': transactions_send, 'receive': transactions_receive}
    return render(request, 'account_detail.html', context)


def transaction(request):
    accounts = Account.objects.all()
    context = {'accounts': accounts}

    if request.method == 'POST':
        sender_id = request.POST['sender']
        receiver_id = request.POST['receiver']
        amount = request.POST['amount']

        if not sender_id or not receiver_id or not amount or amount <= '0':
            messages.error(request, 'All fields are required')
            return redirect('accounts:transaction')

        if sender_id == receiver_id:
            messages.error(request, 'You cannot send money to yourself')
            return redirect('accounts:transaction')

        try:
            amount = Decimal(amount)
        except:
            messages.error(request, 'Invalid amount')
            return redirect('accounts:transaction')

        try:
            with transactiondb.atomic():
                # Lock the sender and receiver accounts
                sender = Account.objects.select_for_update().get(id=sender_id)
                receiver = Account.objects.select_for_update().get(id=receiver_id)

                if sender.balance < amount:
                    messages.error(request, 'This account has insufficient funds')
                    return redirect('accounts:transaction')

                # Perform the transaction
                sender.balance -= amount
                receiver.balance += amount

                sender.save()
                receiver.save()

                # Create the transaction record
                new_transaction = Transaction(
                    sender=sender,
                    receiver=receiver,
                    amount=amount,
                )
                new_transaction.save()

                messages.success(request, 'Transaction successful')

        except Account.DoesNotExist:
            messages.error(request, 'Account not found')
        except Exception as e:
            messages.error(request, f'An error occurred: {str(e)}')

    return render(request, 'transaction.html', context)


def account_search(request):
    query = request.GET.get('search')
    accounts = Account.objects.filter(name__icontains=query)
    paginator = Paginator(accounts, 100)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    total_accounts = accounts.count()
    total_balance = sum([account.balance for account in accounts])
    context = {
        'accounts': page_obj,
        'total_accounts': total_accounts,
        'total_balance': total_balance,
    }
    return render(request, 'list_accounts.html', context)


def error_404(request, exception):
    messages.error(request, 'Page not found')
    return redirect('accounts:list_accounts')


def error_500(request):
    messages.error(request, 'Unknown server error')
    return redirect('accounts:list_accounts')

templates/account_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <h1 class="mb-4">Account Details</h1>
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Name: {{ account.name }}</p>
                        <h5 class="card-title">ID: {{ account.id }}</h5>
                        <p class="card-text">Balance: {{ account.balance }}</p>
                        <a href="{% url 'accounts:list_accounts' %}" class="btn btn-primary">Back to Accounts</a>
                    </div>
                </div>
            </div> 
            <div class="col-md-8 col-sm-12">

                <h1 class="mb-4">Account Transactions</h1>
                <div class="card">
                    <div class="card-body">
                        <h2>Sent Transactions</h2>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Receiver</th>
                                    <th>Amount</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for transaction in send %}
                                <tr>
                                    <td>{{ transaction.receiver.name }}</td>
                                    <td>{{ transaction.amount }}</td>
                                    <td>{{ transaction.date }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        
                        <h2>Received Transactions</h2>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Sender</th>
                                    <th>Amount</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for transaction in receive %}
                                <tr>
                                    <td>{{ transaction.sender.name }}</td>
                                    <td>{{ transaction.amount }}</td>
                                    <td>{{ transaction.date }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div> 
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    

    {% block title %}
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .django-messages {
            position: fixed;
            top: 10px;
            right: 10px;
            z-index: 1000;
        }
        .alert-error{
            background-color: #f8d7da;
            border-color: #f5c6cb;
            color: #721c24;
        }
        .alert-success{
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
        }
        .alert-warning{
            background-color: #fff3cd;
            border-color: #ffeeba;
            color: #856404;
        }
        .alert-info{
            background-color: #d1ecf1;
            border-color: #bee5eb;
            color: #0c5460;
        }
        .preload{
            position: fixed;
            top: 50%;
            left: 50%;
            width: 100%;
            height: 100%;
        }
        
    </style>

    {% block style %}
    {% endblock %}



</head>
<body>

    <div class="preload">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>


    {% if messages %}
    <div class="django-messages">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}




    {% block script %}
    {% endblock %}

    

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function(){
        document.querySelector('.preload').style.display = 'none';

    });
    $('form').submit(function(){
        console.log('submitting form');
        document.querySelector('.preload').style.display = 'fixed';
    });
</script>


</body>
</html>

templates/import_accounts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Import Accounts</h1>
        <form method="post" enctype="multipart/form-data" id="form">
            {% csrf_token %}
            <div class="form-group">
                <label for="csv_file">Upload CSV file:</label>
                <input type="file" class="form-control" id="csv_file" name="csv_file" accept=".csv">
            </div>
            <button type="submit" class="btn btn-primary">Import</button>
        </form>
        <a href="{% url 'accounts:list_accounts' %}" class="btn btn-secondary mt-3">View Accounts</a>
    </div>

    
{% endblock %}

templates/list_accounts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>
List of Accounts
</title>
{% endblock %}
{% block content %}



<div class="container mt-5">
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Total Accounts: {{ total_accounts }}</h5>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Total Balance: {{ total_balance }}</h5>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5">
    <h1 class="mb-4">List of Accounts
    <div class="float-right">
        
        <!---search-->
        <form method="GET" action="{% url 'accounts:account_search' %}">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search by name" name="search" value="{{ request.GET.search }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>

        <a href="{% url 'accounts:import_accounts' %}" class="btn btn-secondary mt-3">Import More Accounts</a>
        <a href="{% url 'accounts:transaction' %}" class="btn btn-secondary mt-3">Transfer Funds</a>
    </div>
    </h1>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Balance</th>
                <th>Details</th>
            </tr>
        </thead>
        {% if accounts %}
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{{ account.id }}</td>
                <td>{{ account.name }}</td>
                <td>{{ account.balance }}</td>
                <td><a href="{% url 'accounts:account_detail' account.slug %}" class="btn btn-info btn-sm">View Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Showing {{ accounts.start_index }} to {{ accounts.end_index }} of {{ accounts.paginator.count }} entries</td>
            </tr>
            <tr>
                <td colspan="4">
                    {% if accounts.paginator.num_pages > 1 %}
                        <nav>
                            <ul class="pagination">
                                {% if accounts.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?search={{ request.GET.search }}&page={{ accounts.previous_page_number }}">Previous</a></li>
                                {% endif %}
                                {% for num in accounts.paginator.page_range %}
                                    <li class="page-item {% if accounts.number == num %}active{% endif %}"><a class="page-link" href="?search={{ request.GET.search }}&page={{ num }}">{{ num }}</a></li>
                                {% endfor %}
                                {% if accounts.has_next %}
                                    <li class="page-item"><a class="page-link" href="?search={{ request.GET.search }}&page={{ accounts.next_page_number }}">Next</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                        {% endif %}
                </td>
            </tr>

        </tfoot>
        {% else %}
        <tr>
            <td colspan="4">No accounts found</td>
        </tr>
        {% endif %}
    </table>

    
</div>

{% endblock %}

templates/transaction.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container mt-5">
        <h1 class="mb-4">Transfer Funds</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="sender">Source Account Name + ID:</label>
                <select required class="form-control" id="sender" name="sender">
                    {% for account in accounts %}
                        <option value="{{ account.id }}">{{ account.name }} - {{account.id}} </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="receiver">Destination Account Name + ID:</label>
                <select required class="form-control" id="receiver" name="receiver">
                    {% for account in accounts %}
                        <option value="{{ account.id }}">{{ account.name }} - {{account.id}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="amount">Amount:</label>
                <input type="text" class="form-control" id="amount" name="amount" required>
            </div>
            <button type="submit" class="btn btn-primary">Transfer</button>
        </form>
        <a href="{% url 'accounts:list_accounts' %}" class="btn btn-secondary mt-3">Back to Accounts</a>
    </div>
{% endblock %}